version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: tdlib:master  # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: docker
    upstream: idawnlight:docker
    mergeMethod: hardreset